version: '3.6'
services:

  goreit-service:
    image: localhost:5000/goreit
    volumes:
      - goreit-service-data:/root
    ports:
      - 8080:8080
    depends_on:
      - 'mongodb'
    networks:
      - GoreIT-internal
    environment:
      SPRING_PROFILES_ACTIVE: "dev"

  mongodb:
    image: mongo:4.0.0
    volumes:
      -  goreit-mongodb-data:/data/db
    ports:
      - 27017:27017
    command: mongod
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root

  pstgrsql:
    image: postgres
    command: postgres -c 'max_connections=1000' -c 'shared_buffers=2GB' -c 'idle_in_transaction_session_timeout=5min'
    volumes:
      - goreit-postgres-data:/var/lib/postgresql/data
    ports:
      - 20002:5432
    environment:
      - POSTGRES_PASSWORD=Lideo123^
      - POSTGRES_DB=goreit
      - PGDATA=postgres


volumes:
  goreit-service-data:
  goreit-mongodb-data:
  goreit-postgres-data:



