mongodb:
  max:
    pool:
      size: 300

spring:
  servlet:
  multipart:
    max-file-size: 3MB
  application:
    name: Goreit
  data:
    mongodb:
      database:  goreit
      authentication-database: admin
      host: mongo.dev
      port: 27017
      password: root
      username: root
  datasource:
    hikari:
      register-mbeans: true
    password: Lideo123^
    url: jdbc:postgresql://postgres.dev:5432/goreit
    username: postgres
  liquibase:
    change-log: "classpath:db/liquibase-master-changelog.xml"
  jpa:
    properties:
      hibernate:
        default_schema: goreit
logging:
  level:
    root: warn
    org:
      springframework:
        web: debug
      hibernate:
        SQL: info
  file: /logs/goreit.log

server:
  port: 8080

ribbon:
  http:
    client:
      enabled=true: