mongodb:
  max:
    pool:
      size: 300

spring:
  servlet:
  multipart:
    max-file-size: 3MB
  application:
    name: GoreIT
  data:
    mongodb:
      database:  goreit
      authentication-database: admin
      host: mongodb
      port: 27017
      password: root
      username: root
  datasource:
    hikari:
      register-mbeans: true
    password: Lideo123^
    url: jdbc:postgresql://postgres:5432/goreit
    username: postgres
  liquibase:
    change-log: "classpath:db/liquibase-master-changelog.xml"
  jpa:
    properties:
      hibernate:
        default_schema: goreit
loggin:
  level:
    root: info
    org:
      springframework:
        web: info
      hibernate:
        SQL: INFO
  file: /logs/goreit.log

server:
  port: 8080