mongodb:
  max:
    pool:
      size: 300

spring:
  servlet:
  multipart:
    max-file-size: 3MB
  application:
    name: Goreit
  data:
    mongodb:
      database:  goreit
      authentication-database: admin
      host: mongo
      port: 27017
      password: root
      username: root

  cloud:
    kubernetes:
      discovery:
        all-namespaces: true

logging:
  level:
    root: warn
    org:
      springframework:
        web: debug
      hibernate:
        SQL: info
  file: /logs/goreit.log

server:
  port: 8082

ribbon:
  http:
    client:
      enabled: true

