apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: prod1
  region: eu-central-1

nodeGroups:
  - name: ng-1
    instanceType: t2.small
    desiredCapacity: 1
    ssh:
      allow: true # will use ~/.ssh/id_rsa.pub as the default ssh key